fieldLayouts:
  e5e90fcc-0555-41d4-bd2b-8250eaada35a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e9d94883-8c23-47a5-9a1e-f5c60c268201 # Business Name
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f75f8992-7717-4d3f-af44-d553d40053c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7c43ddf9-0b09-4e5d-99cc-9cc25fee93bd # Phone Number
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc3eb6fd-4383-414e-98a6-87b15ac44a2f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f86bda1e-c10b-414a-b6d7-fb44923f2326 # Street Address
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7d4dd0c-55a8-4b6a-8a13-88692cb017a9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4983c8df-a87e-4134-bca1-ff42ca8c7628 # Weekday Hours
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72562e81-1413-4f9a-ba85-80a43f85cbc9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2040b384-0884-4c63-83ec-c185dd027653 # Saturday Hours
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81e91106-3af2-4385-baf4-c522165be609
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 06287fe5-1e3a-458f-bb1e-aaebf199c94b # Google Rating
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47d13437-b91a-4584-b229-cb79ed02dc64
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7164911c-9ba5-44e0-9664-e99aa9d8cfc2 # Google Review Count
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0017d49d-8ec1-40e7-b8de-07056cf36965
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1ca619b6-8fb9-4bca-8cd0-cd597a7021c3 # Directions URL
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7eb5200-0568-4826-ad58-badf8f370fae
            userCondition: null
            warning: null
            width: 100
        name: 'Business Details'
        uid: 9c0d2dba-2847-450e-8a17-83b0893f62dc
        userCondition: null
    thumbFieldKey: null
handle: siteSettings
name: 'Site Settings'
sortOrder: 1
