allowLineBreaksInTitles: false
color: null
description: 'A vehicle offer or general request submitted from the website.'
fieldLayouts:
  29face14-68c9-470b-bc78-49cdcb156416:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8dbd2244-8d14-4a3d-97a7-d1deef8c967b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cbb84471-a1aa-45b9-84df-1ebab9ece4a1 # Request Type
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a161cc0-34b8-465c-8a2c-0c776dd0b89d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 90849714-c266-44a2-928b-7d00691014fe # Name
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58032339-5844-4dff-aab8-afe10ea4c7d9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8d0d8037-03ff-4720-b797-1116a49eeb7f # Phone
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f948471-bfb8-44a7-a980-a4ecee83b2e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 69a16738-7a80-4d84-9427-940c9f925c90 # Email
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33a8ac5d-fa12-40a6-959f-6ff4270ba3b2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1b9da689-9595-4422-9757-6bbc111f6150 # Vehicle
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a32ae688-7356-4963-97f6-f2bc7a7b44cc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a50cdc18-80c7-48fe-b473-f1026898f8b7 # Condition
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 056027ce-488e-487e-9b56-93cc010c1e28
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7f4e7440-d21f-4922-84c8-de00233d368c # ZIP Code
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0974d090-3641-42ee-ab90-0b9f418acd06
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 545a32c4-f564-4423-a711-58a3d5e35add # Subject or Part Needed
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78332947-5419-452a-8adc-8073afa084f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e12aa9db-f6bc-4035-ba64-408dd66eb3d9 # Message
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c5292f6-06b3-4c09-9291-fcf8e8de7e19
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d3fead23-46d6-494e-9342-eff0e98a3602 # Source Page
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebd5a1ac-0db9-4885-9271-b7f883b4f476
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 776599d3-6bb0-49d4-b58a-ecff92ab83dd # Complete Submission
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57d50db7-1fb5-49b0-b236-1a5a542c2158
            userCondition: null
            warning: null
            width: 100
        name: Request
        uid: ffcd7db5-69a2-4faf-ac13-49d1ec47dc56
        userCondition: null
    thumbFieldKey: null
handle: inquiry
hasTitleField: true
icon: null
name: Inquiry
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
