columnSuffix: null
handle: contentValue
instructions: 'Edit the text, destination, alternative text, or fallback image URL.'
name: 'Content Value'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
