columnSuffix: null
handle: sectionCssClass
instructions: 'Advanced space-separated classes applied to the section wrapper.'
name: 'Additional CSS Classes'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
