columnSuffix: null
handle: sectionMarkup
instructions: 'Advanced layout template. Content values are managed in Section Content.'
name: 'Section Layout Markup'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 16
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
